//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Comments = new HashSet<Comment>();
            this.Events = new HashSet<Event>();
            this.Events1 = new HashSet<Event>();
            this.Events2 = new HashSet<Event>();
            this.EventUsers = new HashSet<EventUser>();
            this.Friendships = new HashSet<Friendship>();
            this.Friendships1 = new HashSet<Friendship>();
            this.Groups = new HashSet<Group>();
            this.Groups1 = new HashSet<Group>();
            this.Groups2 = new HashSet<Group>();
            this.GroupUsers = new HashSet<GroupUser>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Notifications = new HashSet<Notification>();
            this.Posts = new HashSet<Post>();
            this.Likes = new HashSet<Like>();
        }
    
        public long Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Skype { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string ProfilePicture { get; set; }
        public string CoverPicture { get; set; }
        public Nullable<System.DateTime> LastStatusOn { get; set; }
        public Nullable<byte> StatusID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<short> Privacy { get; set; }
        public Nullable<short> Rating { get; set; }
        public string NickName { get; set; }
        public string Organization { get; set; }
        public string OrganizationLocation { get; set; }
        public string PositionInOrganization { get; set; }
        public Nullable<System.DateTime> OrganizationJoinDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string AboutMe { get; set; }
        public string Relationship { get; set; }
        public string DesireToMeet { get; set; }
        public string TimeZone { get; set; }
        public Nullable<short> Language { get; set; }
        public string Interest { get; set; }
        public string Hobbies { get; set; }
        public string Education { get; set; }
        public Nullable<short> Religion { get; set; }
        public string FavAnimals { get; set; }
        public string FavBooks { get; set; }
        public string FavMusics { get; set; }
        public string FavMovie { get; set; }
        public string favArtist { get; set; }
        public Nullable<short> Smoker { get; set; }
        public Nullable<short> Drinker { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual UserStatu UserStatu { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ConnectedUser ConnectedUser { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Event> Events1 { get; set; }
        public virtual ICollection<Event> Events2 { get; set; }
        public virtual ICollection<EventUser> EventUsers { get; set; }
        public virtual ICollection<Friendship> Friendships { get; set; }
        public virtual ICollection<Friendship> Friendships1 { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Group> Groups1 { get; set; }
        public virtual ICollection<Group> Groups2 { get; set; }
        public virtual ICollection<GroupUser> GroupUsers { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
    }
}
