//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long ID { get; set; }
        public long PostID { get; set; }
        public string Text { get; set; }
        public long UserID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
