//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public long ID { get; set; }
        public long ItemID { get; set; }
        public Nullable<short> ItemLevel { get; set; }
        public short Reason { get; set; }
        public string UserComment { get; set; }
        public Nullable<bool> Processed { get; set; }
        public string AdminComment { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
