//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatu
    {
        public UserStatu()
        {
            this.ConnectedUsers = new HashSet<ConnectedUser>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public byte ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<ConnectedUser> ConnectedUsers { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
